name: dynamic-certigo-build

on:
  push:
    branches: 
      - master
      - develop
      - 'feature/**'
    paths-ignore:
      - README.md

jobs:
  build:
    name: Build image
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t dynamic-certigo .
